<?php

namespace AppBundle\Repository;

/**
 * ControleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ControleRepository extends \Doctrine\ORM\EntityRepository
{
}
