<?php

namespace AppBundle\Repository;

/**
 * HospitalisationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HospitalisationRepository extends \Doctrine\ORM\EntityRepository
{
}
